version: '3'
services:
  mysql:
    image: mysql:8.0.17
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: todos
      
  todo-app-backend:
    image: todo-app-backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
